### ISSUE TITLE
[Feature request] Docker images

### ISSUE THREAD

**Issue by azbarcea** [LibreHealthIO/lh-ehr#1255]
# Feature Description

Develop and support Dockerfiles to ease settinging up LibreHealth EHR. The Release _pipeline_ can build the docker images and offer them as official images.

Together with `docker-compose.yml`, they can offer a platform ease development, testing, evaluation process, deployments.

The goal is to have an image that would allow somebody to test and deploy (using Docker) `librehealth` in a matter of minutes (if not seconds). The trend is given by the multitude of [`docker` official images](https://hub.docker.com/explore/) provided by various FOSS communities.

**Comment by teryhill** [comment]
Wrong group. this is the EHR group not the radiology group.

**Comment by tmccormi** [comment]
@teryhill It is the correct Group.  Alex is working on the UNF grant to containerize LibreEHR

**Comment by tmccormi** [comment]
Not sure why the "Radiology" note is here though

**Comment by azbarcea** [comment]
I thought multiple _profiles_ (sets of data) would be beneficial ...

**Comment by tmccormi** [comment]
I'm afraid we have no idea what you are talking about.   Very few of us have any experience with Docker, so we'd love to hear what this means.

**Comment by azbarcea** [comment]
If the [README.md](https://github.com/LibreHealthIO/lh-ehr/pull/1256/files#diff-a489144702a723431811d56a3c44690a) is not sufficient, I can also provide the screenshots.

There are few _Warnings_. I look forward for advice how set it up better :sparkles:

**Comment by muarachmann** [comment]
@azbarcea are you trying to install EHR using docker???

**Comment by azbarcea** [comment]
I think the actual installer is `setup.php`. Yes, EHR will run in `Docker`.

**Comment by muarachmann** [comment]
And what are the advantages/disadvantages of this feature?? we will love to hear about docker

**Comment by azbarcea** [comment]
It adds support for another _packaging_ type (`docker`) and adds another distribution channel. If automated and integrated with docker official images in brings visibility and support for cloud deployments.

Also, if anybody would like to try LibreHealth, it would take literately 5 minutes to have an instance running (pre-requisite docker) without the need to know anything about LibreHealth. You can also see it as another way to achieve what `lh-toolkit` is trying to automate with deployments (not yet as feature rich, though).

It enables continuous integration and performance testing by automating deployments.

It enabled LibreHealth Operation on Linux, w/ Docker.

- _etc._

**Comment by azbarcea** [comment]
In order to have _all configuration data to be stored outside of the application container_, what is the list of all these configuration folders (or individual files), that the community would like to see them in a volume? I presume not all configurations is beneficial to be outside the container image, because if it is, the upgrade could become trickier. The data from a volume doesn't get overwritten during container. 

Any advice is greatly appreciated.

**Comment by tmccormi** [comment]
Essentially almost all of the contents of the sites/* directory is stuff that should be on a shared volume. At least the following should be separated (this will require us to make some minor code changes;

Alex, not expecting you to do these code changes.  MI2 will do these.  If you have some best practice hints happy to see them.

sqlconf.php is the Database access config

This start empty at install time:
sites/[SITENAME]/documents
sites/[SITENAME]/edi
sites/[SITENAME]/era
sites/[SITENAME]/logs
gacl/admin/templates_c

These have "defaults" that can be edited by the user as some level and will need some kind of method to save them changes (if changed):
sites/[SITENAME]/letter_templates
sites/[SITENAME]/faxcover.txt
sites/[SITENAME]/faxtitle.eps
sites/[SITENAME]/images
sites/[SITENAME]/letter_templates
sites/[SITENAME]/menu_data.json
sites/[SITENAME]/readme_rx_printtofax.txt
sites/[SITENAME]/referral_template.html
sites/[SITENAME]/roles.json
sites/[SITENAME]/rx_addendum.txt
sites/[SITENAME]/statement.inc.php
sites/[SITENAME]/filemanager/files
** filemanager/*.php code and assets should be moved OUT of the sites dir

sites/[SITENAME]/LBF -> these are plugin modules and should be moved to the modules/ directories

**Comment by aethelwulffe** [comment]
sites/filemanager is a SANDBOXED application.  Either it can function as 
per-site code, or as cross-site code, but not both.

**Comment by tmccormi** [comment]
@aethelwulffe  couldn't we sandbox access to the the filemanager/files dir but not the code that writes to it?

**Comment by tafodinho** [comment]
@azbarcea I will be interesting in working with you on "dockering" up EHR

**Comment by azbarcea** [comment]
@tafodinho: glad to have any of your feedback or contributions. Feel free to create PR against the #1256, or comment on that PR.

**Comment by azbarcea** [comment]
> Essentially almost all of the contents of the sites/* directory is stuff that should be on a shared volume. At least the following should be separated (this will require us to make some minor code changes;
> 
> we support mulit-hosted databases out of one code base, so 'sites/[SITENAME]/* where the default site name is "default' but could be anything
> 
> Alex, not expecting you to do these code changes. MI2 will do these. If you have some best practice hints happy to see them.
> 
> gacl/admin/templates_c (compiled templates)
> sqlconf.php is the Database access config
> 
> These start empty at install time and are written to by the application:
> sites/[SITENAME]/documents
> sites/[SITENAME]/edi
> sites/[SITENAME]/era
> sites/[SITENAME]/logs
> 
> These have "defaults" that can be edited by the user at some level and will need some kind of method to save the changes (if changed):
> sites/[SITENAME]/letter_templates
> sites/[SITENAME]/faxcover.txt
> sites/[SITENAME]/faxtitle.eps
> sites/[SITENAME]/images
> sites/[SITENAME]/letter_templates
> sites/[SITENAME]/menu_data.json
> sites/[SITENAME]/readme_rx_printtofax.txt
> sites/[SITENAME]/referral_template.html
> sites/[SITENAME]/roles.json
> sites/[SITENAME]/rx_addendum.txt
> sites/[SITENAME]/statement.inc.php
> sites/[SITENAME]/filemanager/files
> ** filemanager/*.php code and assets should be moved OUT of the sites dir
> 
> sites/[SITENAME]/LBF -> these are plugin modules and should be moved to the modules/ directories

@tmccormi, the best-practices are driven by the lifecycle of the artifacts. I always think of 4 different types of them:
* code
* config
* data
* _docs_

For the _docs_ part, you don't care to have it in this container, maybe a different one, with `lh-toolkit`, API etc. So lets not discuss here about it :smile: 

For **config**, there are 3 different ideas:
* either do Configuration Management using docker images, this require a image rebuild every single time your configuration changes.
* or do Configuration Management using volumes and orchestrating the config outside of `docker`. In this case one can leverage the same Config. Management. from the Infra (Puppet, Chef, Ansible, custom scripts in python, bash etc)
* or use a docker orchestration framework (e.g. Kubernetes, _Rancher_, _OpenShift_. _Terraform_ etc).

For **data**, is always volumes, if the app can architect itself in a way that data and config is obvious, which volumes are required is easy. Otherwise, the community will have different interpretations about them, especially when some configurations go in the DB.

And last, **code**, which best is to use the OS package manager (*deb* with *apt*, *rpm* with *yum* etc).  Not always your code is nicely supported, with releases automated to build packages, and then, one just follows the Development conventions.

Hope it helps ...

**Comment by aethelwulffe** [comment]
We need to pull the MIPS stuff as well as that file manager out and put 
it into a separate repo.  The file manager, which is a per-site thing, 
is so sandboxed it can't breath, which is why it was deployed there.

I will get it out very soon.  None of the required update PR's for the 
module were getting merged anyway.

**Comment by aethelwulffe** [comment]
Actually, all the letter templates and stuff, *most of which is pure 
junk*, should be pared down massively.  We do not need print-to-fax 
system bits left over from when there was actually some sort of hylafax 
component that I think can't be used any more anyway.  All else need not 
actually exist until it is actually required, and most folks don't use.

The menu, as recently discussed, should have the JSON version pulled out 
and go with the pure database driven version. @terryhill and some of us 
still have that code around.  It will make menu configuration much easier.

GACL and the remaining SMARTY template stuff needs to be replaced.  We 
barely use GACL, and a few simple functions could replace the whole 
thing and give us something modern, slim, and *comprehensible*.  No 
reason why we could not reuse or replace existing function calls.  The 
ACL checks are hard-coded, the access groups are basically undocumented, 
and even the variable names and arguments are incomprehensible.

LBF should be moved, yes, but it is, to our great pain, a CORE module as 
it drives the demographics and a lot of other things. It is on the 
"advance to the 21st century" chopping block.

-essentially, there is nothing in /libraries or /interface that 
shouldn't actually be moved...ultimately...into /modules.  It has been a 
long, hard migration with a stranglevine refactor-in-place approach, and 
we have come far, but we need a lot more cleanup before we do any more 
UI fanciness.  I am willing to help prioritize cleaning up the /sites 
directory myself.

**Comment by azbarcea** [comment]
This is all great news. As I understand it involves now refactoring (clean-up) in the code-base, too. Does this container, as it is, help in any way?

**Comment by aethelwulffe** [comment]
I actually have no idea why you would want an image that contains 
pre-set dependencies when you are trying to run a project that keeps up 
with the base LAMP stack and nothing else myself.  If we were including 
other packages with cool useful stuff that is non-canonical, like the 
latest and greatest PHPmyAdmin, then sure, but we are just running a 
basic up-to-date here.  I am of the understanding that other folks want 
the docker container thingie, so...

Everything involves clean-up around here.  We have some stuff about 14 
years overdue yet to go.  We are only going to concentrate on the 
refactoring that allows the /sites directory to work as needed.  This 
puts a little damper on a certification effort, but best put the QA 
stuff on a side-burner I suppose.

**Comment by azbarcea** [comment]
> I actually have no idea why you would want an image that contains pre-set dependencies when you are trying to run a project that keeps up with the base LAMP stack and nothing else myself.  If we were including other packages with cool useful stuff that is non-canonical, like the latest and greatest PHPmyAdmin, then sure, but ...

I think you're proposing different container stacks, based on different use cases. This container doesn't solve your developer (`PHPmyAdmin`) needs.

Feel free to add more details and we all should be able to prioritize.

**Comment by aethelwulffe** [comment]
Oh, I am not actually proposing multiple container building (at this 
time).  You are doing right by concentrating on an MVP here. Chances are 
that it will be the only one that is needed.

**Comment by azbarcea** [comment]
@tmccormi, @aethelwulffe, @robbyoconnor, @tafodinho - with latest commits, I think we have an initial, workable solution, for having LibreHealth EHR running in a `docker` container.

I hope you can find these containers useful. Do you use LibreHealth with `docker` currently? Do you see yourself using `docker` to manage `librehealth-ehr` deployments and upgrades or even for development/testing ?

**Comment by robbyoconnor** [comment]
I plan to review your PR tomorrow Monday.

**Comment by azbarcea** [comment]
thank you @robbyoconnor for your reviews. I addressed them at the [pull-request:1256](#1256) level.

**Comment by robbyoconnor** [comment]
@azbarcea one of the things you missed is the fact that sites didn't have a volume created. I tweaked your docker image but you did a pretty good job! It just got quicker for me to fix the remaining minor issues myself rather than waiting for the feedback loop. 

I published the images to the GitLab container registry using GitLab CI and updated the docs and for now, it's one image -- but kudos for making it as easy as passing a build arg to support however many PHP version we choose! I also pulled the default site dir and config for docker to pretty much make it automated setup :) I really should set up one that is an empty EHR database with an admin user so it becomes truly turnkey!

**Comment by robbyoconnor** [comment]
and we can add adminer in a separate container -- that's pretty easy to do :)

**Comment by tmccormi** [comment]
@robbyoconnor Regarding: I really should set up one that is an empty EHR database with an admin user so it becomes truly turnkey!

--> I agree, this is actually how we build the windows XAMPP installation package.  It's one preinstalled zip file with the empty EHR DB.

**Comment by robbyoconnor** [comment]
I'll get right on that and set that up!

**Comment by robbyoconnor** [comment]
Closing this.
